# Generated by Django 6.0 on 2025-12-30 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviacao', models.CharField(help_text='Ex: HMI, PMA', max_length=20, verbose_name='Sigla / Abreviação')),
                ('nome', models.CharField(help_text='Ex: Hospital Med Imagem', max_length=100, verbose_name='Nome da Unidade')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=20, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['abreviacao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('CAPEX', 'CAPEX (Investimento/Obras/Bens)'), ('OPEX', 'OPEX (Custeio/Manutenção/Materiais)')], max_length=10)),
                ('descricao_servico', models.TextField(verbose_name='Descrição do Material/Serviço')),
                ('fornecedor', models.CharField(max_length=150)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anexo_orcamento', models.FileField(upload_to='orcamentos/%Y/%m/', verbose_name='Orçamento (PDF)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SOLICITADO', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado (Ordem Gerada)'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído (NF Lançada)')], default='RASCUNHO', max_length=20)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.centrocusto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('numero_fluig', models.CharField(help_text='ID do processo no Fluig se houver', max_length=50, verbose_name='Número Fluig')),
                ('data_emissao', models.DateField()),
                ('arquivo_nf', models.FileField(upload_to='notas_fiscais/%Y/%m/')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('responsavel_lancamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ordem_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_fiscal', to='home.ordemcompra')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('usuario_sistema', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='home.solicitante'),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.unidade'),
        ),
    ]
