# Generated by Django 6.0 on 2025-12-31 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abreviacao', models.CharField(help_text='Ex: HMI, PMA', max_length=20, verbose_name='Sigla / Abreviação')),
                ('nome', models.CharField(help_text='Ex: Hospital Med Imagem', max_length=100, verbose_name='Nome da Unidade')),
                ('razao_social', models.CharField(max_length=150, verbose_name='Razão Social')),
                ('cnpj', models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=20, verbose_name='CNPJ')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['abreviacao'],
            },
        ),
        migrations.CreateModel(
            name='OrdemCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_os', models.CharField(max_length=50, verbose_name='Número da OS')),
                ('data_os', models.DateField(verbose_name='Data da OS')),
                ('setor_execucao', models.CharField(max_length=100, verbose_name='Setor de Execução')),
                ('objetivo_compra', models.CharField(choices=[('IMOBILIZADO', 'Aquisição de Bens Imobilizados'), ('MATERIAL', 'Compra de Material (Direto/Indireto)'), ('OBRAS', 'Obras'), ('REFORMA_OPEX', 'Reforma (OPEX)'), ('REFORMA_CAPEX', 'Reforma (CAPEX)'), ('MANUT_PREVENTIVA', 'Manutenção Preventiva'), ('MANUT_CORRETIVA', 'Manutenção Corretiva')], max_length=30)),
                ('especialidade', models.CharField(choices=[('ELETRICA', 'Elétrica'), ('HIDRAULICA', 'Hidráulica'), ('ENG_CLINICA', 'Engenharia Clínica'), ('OBRAS_CIVIL', 'Obras / Civil'), ('OPERACIONAL', 'Operacional'), ('REFRIGERACAO', 'Refrigeração'), ('GASES', 'Gases Medicinais / Rede de Gases'), ('UTILITIES', 'Utilities (Energia/Água/Esgoto)')], max_length=30)),
                ('conta_contabil', models.CharField(choices=[('AGUA_ESGOTO', 'Água e Esgoto (OPEX)'), ('ENERGIA', 'Energia Elétrica (OPEX)'), ('GASES_MED', 'Gases Medicinais (OPEX)'), ('ALUGUEL_EQUIP', 'Aluguel de Equipamentos (OPEX)'), ('MANUT_PREDIAL', 'Manutenção Predial (OPEX)'), ('MANUT_EQUIP', 'Manutenção de Equipamentos (OPEX)'), ('MANUT_MOVEIS', 'Manutenção de Móveis e Utensílios (OPEX)'), ('INVESTIMENTO', 'Investimento / CAPEX (Outros)')], max_length=30)),
                ('classificacao', models.CharField(choices=[('CAPEX', 'CAPEX (Investimento/Obras/Bens)'), ('OPEX', 'OPEX (Custeio/Manutenção/Materiais)')], max_length=10)),
                ('tipo_contrato', models.CharField(choices=[('FIXO', 'Fixo / Recorrente'), ('SPOT', 'Spot / Pontual')], default='SPOT', max_length=10, verbose_name='Tipo de Contrato')),
                ('descricao_servico', models.TextField()),
                ('justificativa', models.TextField()),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('fornecedor', models.CharField(max_length=150)),
                ('email_fornecedor', models.EmailField(blank=True, max_length=254, null=True)),
                ('condicao_pagamento', models.CharField(max_length=100)),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('anexo_orcamento', models.FileField(upload_to='orcamentos/%Y/%m/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('SOLICITADO', 'Aguardando Aprovação'), ('APROVADO', 'Aprovado (Ordem Gerada)'), ('REPROVADO', 'Reprovado'), ('CONCLUIDO', 'Concluído (NF Lançada)')], default='RASCUNHO', max_length=20)),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True)),
                ('motivo_reprovacao', models.TextField(blank=True, null=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aprovacoes', to=settings.AUTH_USER_MODEL)),
                ('centro_custo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.centrocusto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nf', models.CharField(max_length=50, verbose_name='Número da NF')),
                ('numero_fluig', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número Fluig (Legado)')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('valor_final', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Valor Final da Nota')),
                ('tipo_lancamento', models.CharField(choices=[('FLUIG', 'Com Pedido Fluig'), ('REGULARIZACAO', 'Regularização'), ('MEDICAO', 'Medição de Contrato'), ('DIVERSOS', 'Pagamentos Diversos')], default='FLUIG', max_length=20, verbose_name='Tipo de Lançamento')),
                ('plaqueta', models.CharField(blank=True, help_text='Obrigatório se for CAPEX', max_length=50, null=True, verbose_name='Plaqueta (Ativo Imobilizado)')),
                ('arquivo_nf', models.FileField(upload_to='notas_fiscais/%Y/%m/')),
                ('data_lancamento', models.DateTimeField(auto_now_add=True)),
                ('responsavel_lancamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ordem_compra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_fiscal', to='home.ordemcompra', verbose_name='Ordem de Compra / Fluig')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / WhatsApp')),
                ('usuario_sistema', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='home.solicitante'),
        ),
        migrations.AddField(
            model_name='ordemcompra',
            name='unidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.unidade'),
        ),
    ]
