# Generated by Django 6.0 on 2025-12-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitante',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone / WhatsApp'),
        ),
    ]
